### ISSUE TITLE
3 errors when freshly added to a project

### ISSUE THREAD

**Issue by not-holar** [plabayo/tokio-graceful#4]
![image](https://github.com/plabayo/tokio-graceful/assets/58831297/70f6c8f3-e9ea-46bf-8cbc-9ce830f6463b)

Cargo.toml
```toml
[dependencies]
tokio-graceful = "0.1.4"
```
